apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: podinfo
  name: podinfo
  namespace: lab
spec:
  ports:
  - name: 8080-9898
    port: 8080
    protocol: TCP
    targetPort: 9898
  selector:
    app: podinfo
  type: ClusterIP
status:
  loadBalancer: {}
