# This is a basic workflow to help you get started with Actions

name: validation-k8s-yaml

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: validate kubernetes yaml in cluster folder 
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: clusters
          token: ${{ secrets.GITHUB_TOKEN }}
          strict: false

      - name: validate kubernetes yaml in infrastructure folder 
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: infrastructure
          token: ${{ secrets.GITHUB_TOKEN }}
          strict: false

      - name: validate kubernetes yaml in apps folder 
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: apps
          token: ${{ secrets.GITHUB_TOKEN }}
          strict: false
          
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2.4.0

